# Generated by Django 5.2.12 on 2026-06-01 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_section'),
        ('faculty', '0006_remove_section_mentor_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionClassTeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='academics.section')),
                ('teacher', models.ForeignKey(limit_choices_to=models.Q(('role__in', ['Faculty', 'Mentor'])), on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section__name', '-academic_year'],
                'unique_together': {('section', 'academic_year')},
            },
        ),
    ]
